# Generated by Django 4.1 on 2022-08-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeMitra_app', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeMitra_app.staff')),
            ],
        ),
    ]
